baseURL = "http://127.0.0.1:5500/"
languageCode = "en-gb"
title = "orangc's blog"
theme="archie"
copyright = "orangc"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "orangc"

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "occasional posts about anything and everything"
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support
    customcss = ["/css/uwu.css"]

# Social Tags

[[params.social]]
# name = "GitHub"
# icon = "github"
# url = "https://github.com/orangci"

# Main menu Items

[[menu.main]]
name = "/home"
url = "https://orangc.xyz"
weight = 1

[[menu.main]]
name = "/posts"
url = "/posts"
weight = 2